on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare version info
        id: version
        run: |
          timestamp=$(date -u +"%Y%m%d%H%M")
          commit=$(echo "${GITHUB_SHA}" | cut -c1-7)
          branch_name=$(echo "${GITHUB_REF}" | awk -F'/' '{print $NF}' | cut -c1-4)
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "commit=$commit" >> $GITHUB_OUTPUT
          echo "file_prefix=${timestamp}-${commit}" >> $GITHUB_OUTPUT
          TIMESTAMP="$timestamp" COMMIT="$commit" bin/get_version.sh "$branch_name" "$commit"
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West init
        run: west init -l config
      - name: West update
        run: west update
      - name: West zephyr-export
        run: west zephyr-export
      - name: Build firmware (both halves)
        env:
          TIMESTAMP: ${{ steps.version.outputs.timestamp }}
          COMMIT: ${{ steps.version.outputs.commit }}
          BUILD_RIGHT: "true"
        run: ./bin/build.sh
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            firmware/${{ steps.version.outputs.file_prefix }}-left.uf2
            firmware/${{ steps.version.outputs.file_prefix }}-right.uf2
